--- #YAML:1.0
name:                WebService-UPS
version:             0.1
abstract:            ~
license:             ~
author:              
    - Kyle Brandt <kyle@kbrandt.com>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Data::Dumper:                  2.12114
    HTTP::Request::Common:         5.811
    LWP::UserAgent:                5.81
    Mouse:                         0.19
    XML::Simple:                   2.18
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
